openapi: 3.0.0
info:
  title: Información de Ciudades y Departamentos
  description: API para obtener información de ciudades y departamentos
  version: 1.0.0
tags:
  - name: 'Ciudades - Departamentos'
    description: 'Operaciones relacionadas con las ciudades y departamentos'

paths:
  /api/city/cities:
    get:
      summary: Obtener lista de ciudades
      tags:
        - 'Ciudades - Departamentos'
      security:
        - apiKeyQuery: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  cities:
                    type: array
                    items:
                      $ref: '#/components/schemas/City'

  /api/city/departments:
    get:
      summary: Obtener lista de departamentos
      tags:
        - 'Ciudades - Departamentos'
      security:
        - apiKeyQuery: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  departments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Department'

components:
  schemas:
    City:
      type: object
      properties:
        city:
          type: string
          description: Nombre de la ciudad
        c_city:
          type: string
          description: Nombre de la ciudad con caracteres eliminados

    Department:
      type: object
      properties:
        department:
          type: string
          description: Nombre del departamento
