openapi: 3.0.0
info:
  title: Operaciones de Órdenes
  description: API para gestionar órdenes de pedido
  version: 1.0.0
tags:
  - name: 'Órdenes - hook'
    description: 'Operaciones relacionadas con las órdenes de pedido'

paths:
  /orders:
    get:
      summary: Obtener todas las órdenes
      tags:
        - 'Órdenes - hook'
      security:
        - apiKeyQuery: []

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'

  /modifyorder:
    post:
      summary: Modificar una orden existente
      tags:
        - 'Órdenes - hook'
      security:
        - apiKeyQuery: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderPost'
      responses:
        '200':
          description: OK
        '400':
          description: Petición inválida

components:
  schemas:
    OrderPost:
      type: object
      properties:
        response_code:
          type: integer
          description: Código de respuesta
        response_message:
          type: string
          description: Mensaje de respuesta
        order_ref:
          type: string
          description: Referencia del pedido
        order_id:
          type: string
          description: ID del pedido
        state:
          type: integer
          description: Estado del pedido
          
    Order:
      type: object
      properties:
        order_ref:
          type: integer
          description: ID de referencia del pedido (clave primaria)
        id_shopify:
          type: string
          description: ID del pedido en Shopify
        order_id:
          type: string
          description: ID del pedido en HistoWeb
        order_date:
          type: string
          description: Fecha del pedido
        order_modified:
          type: string
          description: Fecha de modificación del pedido
        order_status:
          type: string
          description: Estado del pedido
        payment_method:
          type: string
          description: Método de pago
        transaction_id:
          type: string
          description: ID de transacción
        customer_ip_address:
          type: string
          description: Dirección IP del cliente
        customer_user:
          type: integer
          description: ID de usuario del cliente
        billing_cedula:
          type: string
          description: Cédula de facturación
        billing_first_name:
          type: string
          description: Nombre de facturación
        billing_last_name:
          type: string
          description: Apellido de facturación
        billing_email:
          type: string
          description: Email de facturación
        billing_phone:
          type: string
          description: Teléfono de facturación
        billing_address_1:
          type: string
          description: Dirección de facturación línea 1
        billing_address_2:
          type: string
          description: Dirección de facturación línea 2
        billing_city:
          type: string
          description: Ciudad de facturación
        billing_typedcity:
          type: string
          description: Ciudad de facturación escrita
        billing_zona:
          type: string
          description: Zona de facturación
        billing_state:
          type: string
          description: Estado de facturación
        billing_country:
          type: string
          description: País de facturación
        shipping_first_name:
          type: string
          description: Nombre de envío
        shipping_last_name:
          type: string
          description: Apellido de envío
        shipping_address_1:
          type: string
          description: Dirección de envío línea 1
        shipping_address_2:
          type: string
          description: Dirección de envío línea 2
        shipping_city:
          type: string
          description: Ciudad de envío
        shipping_typedcity:
          type: string
          description: Ciudad de envío escrita
        shipping_zona:
          type: string
          description: Zona de envío
        shipping_state:
          type: string
          description: Estado de envío
        shipping_country:
          type: string
          description: País de envío
        order_total:
          type: integer
          description: Total del pedido
        cupon_code:
          type: string
          description: Código de cupón
        branch_description:
          type: string
          description: Descripción de la sucursal
        branch_id:
          type: string
          description: ID de la sucursal
        state:
          type: integer
          description: Estado del pedido
        shipping_notes:
          type: string
          description: Notas de envío
        order_items:
          type: array
          items:
            type: object
            properties:
              product_id:
                type: string
                description: ID del producto
              order_item_name:
                type: string
                description: Nombre del producto
              sku:
                type: string
                description: SKU del producto
              pa_sucursal:
                type: string
                description: Sucursal de envío
              unitario_coniva:
                type: integer
                description: Precio unitario con IVA
              valor_dcto:
                type: integer
                description: Valor del descuento
              valor_bruto:
                type: integer
                description: Valor bruto
              qty:
                type: integer
                description: Cantidad
              line_total:
                type: integer
                description: Total de línea
              cupon_hw:
                type: integer
                description: Cupón para HistoWeb
              cupon_ue:
                type: integer
                description: Cupón UE

OrderPost:
      type: object
      properties:
        response_code:
          type: integer
          description: Código de respuesta
        response_message:
          type: string
          description: Mensaje de respuesta
        order_ref:
          type: string
          description: Referencia del pedido
        order_id:
          type: string
          description: ID del pedido
        state:
          type: integer
          description: Estado del pedido

securitySchemes:
  formAuth:
    type: http
    scheme: form