openapi: 3.0.0
info:
  title: Información de Despachos
  description: API para obtener información de despachos
  version: 1.0.0
tags:
  - name: 'Despachos'
    description: 'Operaciones relacionadas con los despachos'

paths:
  /api/dispatch/list:
    get:
      summary: Obtener lista de despachos
      tags:
        - 'Despachos'
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
          description: Número de página
      security:
        - apiKeyQuery: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  dispatches:
                    type: array
                    items:
                      $ref: '#/components/schemas/Dispatch'
                  totalPages:
                    type: integer
                    description: Número total de páginas

  /api/dispatch/create:
    post:
      summary: Crear un nuevo despacho
      tags:
        - 'Despachos'
      requestBody:
        description: Datos del nuevo despacho
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DispatchCreate'
      security:
        - apiKeyQuery: []
      responses:
        '201':
          description: Despacho creado exitosamente

  /api/dispatch/update:
    put:
      summary: Actualizar un despacho existente
      tags:
        - 'Despachos'
      requestBody:
        description: Datos actualizados del despacho
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DispatchUpdate'
      security:
        - apiKeyQuery: []
      responses:
        '200':
          description: Despacho actualizado exitosamente

  /api/dispatch/delete:
    delete:
      summary: Eliminar un despacho
      tags:
        - 'Despachos'
      requestBody:
        description: ID del despacho a eliminar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DispatchDelete'
      security:
        - apiKeyQuery: []
      responses:
        '204':
          description: Despacho eliminado exitosamente

components:
  schemas:
    Dispatch:
      type: object
      properties:
        id:
          type: integer
          description: ID del despacho
        country:
          type: string
          description: País
        department:
          type: string
          description: Departamento
        city:
          type: string
          description: Ciudad
        geolocation:
          type: boolean
          description: Indica si la geolocalización está activada
        location:
          type: string
          description: Ubicación del despacho

    DispatchCreate:
      type: object
      properties:
        country:
          type: string
          description: País
        department:
          type: string
          description: Departamento
        city:
          type: string
          description: Ciudad
        geolocation:
          type: boolean
          description: Indica si la geolocalización está activada

    DispatchUpdate:
      type: object
      properties:
        id:
          type: integer
          description: ID del despacho a actualizar
        country:
          type: string
          description: Nuevo país
        department:
          type: string
          description: Nuevo departamento
        city:
          type: string
          description: Nueva ciudad
        geolocation:
          type: boolean
          description: Indica si la geolocalización está activada
        location:
          type: string
          description: Nueva ubicación del despacho

    DispatchDelete:
      type: object
      properties:
        id:
          type: integer
          description: ID del despacho a eliminar
