openapi: 3.0.0
info:
  title: Información de Procedimientos
  description: API para obtener información de procedimientos
  version: 1.0.0
tags:
  - name: 'Procedimientos'
    description: 'Operaciones relacionadas con los procedimientos en Shopify'
  - name: 'Procedimientos'
    description: 'Operaciones relacionadas con los procedimientos en Histoweb'

paths:
  /api/product/procedures:
    get:
      summary: Obtener lista de procedimientos de Shopify
      tags:
        - 'Procedimientos'
      security:
        - apiKeyQuery: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcedureListShopify'

  /api/product/proceduresHW:
    get:
      summary: Obtener lista de procedimientos de Histoweb
      tags:
        - 'Procedimientos'
      security:
        - apiKeyQuery: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcedureListHistoweb'

components:
  schemas:
    ProcedureListShopify:
      type: object
      properties:
        procedures:
          type: array
          items:
            $ref: '#/components/schemas/ProcedureShopify'

    ProcedureListHistoweb:
      type: object
      properties:
        procedures:
          type: array
          items:
            $ref: '#/components/schemas/ProcedureHistoweb'

    ProcedureShopify:
      type: object
      properties:
        id:
          type: integer
          description: ID del procedimiento
        product_type:
          type: string
          description: Tipo de procedimiento
        vendor:
          type: string
          description: Vendedor del procedimiento
        title:
          type: string
          description: Título del procedimiento
        status:
          type: string
          description: Estado del procedimiento
        published:
          type: boolean
          description: Indica si el procedimiento está publicado
        tags:
          type: string
          description: Etiquetas del procedimiento
        published_at:
          type: string
          description: Fecha de publicación del procedimiento
        variants:
          type: array
          items:
            $ref: '#/components/schemas/Variant'

    ProcedureHistoweb:
      type: object
      properties:
        title:
          type: string
          description: Título del procedimiento
        body_html:
          type: string
          description: Descripción HTML del procedimiento
        product_type:
          type: string
          description: Tipo de procedimiento
        vendor:
          type: string
          description: Vendedor del procedimiento
        status:
          type: string
          description: Estado del procedimiento
        template_suffix:
          type: string
          description: Sufijo de plantilla
        published:
          type: boolean
          description: Indica si el procedimiento está publicado
        tags:
          type: string
          description: Etiquetas del procedimiento
        variants:
          type: array
          items:
            $ref: '#/components/schemas/Variant'
